/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Dialog1 from "./dialog/Dialog1"
import Dialog2 from "./dialog/Dialog2"
import HallScene from "./script/HallScene"
import Dialog from "./script/Dialog"
import GameControl from "./script/GameControl"
import Bullet from "./script/Bullet"
import DropBox from "./script/DropBox"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="test/HallScene.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=false;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("dialog/Dialog1.ts",Dialog1);
        reg("dialog/Dialog2.ts",Dialog2);
        reg("script/HallScene.ts",HallScene);
        reg("script/Dialog.ts",Dialog);
        reg("script/GameControl.ts",GameControl);
        reg("script/Bullet.ts",Bullet);
        reg("script/DropBox.ts",DropBox);
    }
}
GameConfig.init();