/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui.views.Alert {
    export class AwardUI extends Laya.Dialog {
		public award:Laya.Label;
		public btnFaq:Laya.Button;
		public awardType:Laya.List;
		public winnerList:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Award");
        }
    }
    export class ChatUI extends Laya.Dialog {
		public chatTab:Laya.Tab;
		public chatCon:Laya.ViewStack;
		public chatTextList:Laya.List;
		public chatEmoList:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Chat");
        }
    }
    export class CommonUI extends Laya.Dialog {
		public noticeAgain:Laya.CheckBox;
		public btnConfirm:Laya.Button;
		public tipsText:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Common");
        }
    }
    export class ExchangeUI extends Laya.Dialog {
		public balance:Laya.Label;
		public exchangeValue:Laya.Label;
		public btnExchange:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Exchange");
        }
    }
    export class GainUI extends Laya.Dialog {
		public gainBox:Laya.Box;
		public gameCoin:Laya.Label;
		public detailsList:Laya.List;
		public btnGain:Laya.Button;
		public noData:Laya.Image;
		public btnShowOther:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Gain");
        }
    }
    export class GuideUI extends Laya.Dialog {
		public btnSkip:Laya.Button;
		public helpWarp:Laya.Box;
		public helpList:Laya.ViewStack;
		public bomb:Laya.Label;
		public wu_hua:Laya.Label;
		public si_hua:Laya.Label;
		public niu_niu:Laya.Label;
		public niu_ba:Laya.Label;
		public niu_yi:Laya.Label;
		public niu_lin:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Guide");
        }
    }
    export class OperateListUI extends Laya.Dialog {
		public operateList:Laya.List;
		public noData:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/OperateList");
        }
    }
    export class OperateSetupUI extends Laya.Dialog {
		public operateAmount:Laya.Label;
		public userConfig:Laya.RadioGroup;
		public operateTimes:Laya.Label;
		public tips_1:Laya.Label;
		public autoQueue:Laya.CheckBox;
		public tips_2:laya.html.dom.HTMLDivElement;
		public btnOperate:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/OperateSetup");
        }
    }
    export class PlayerListUI extends Laya.Dialog {
		public playerList:Laya.List;
		public online:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/PlayerList");
        }
    }
    export class PoolRuleUI extends Laya.Dialog {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/PoolRule");
        }
    }
    export class PrizeUI extends Laya.Dialog {
		public textBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Prize");
        }
    }
    export class PropUI extends Laya.Dialog {
		public avatar:Laya.Image;
		public userName:Laya.Label;
		public userScore:Laya.Label;
		public btnSitdown:Laya.Button;
		public propList:Laya.List;
		public sendToAll:Laya.CheckBox;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Prop");
        }
    }
    export class RechargeUI extends Laya.Dialog {
		public rechargeContent:Laya.Label;
		public rechargeTab:Laya.Tab;
		public btnShowKeyboard:Laya.Image;
		public rechargeValue:Laya.Label;
		public btnRecharge:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Recharge");
        }
    }
    export class ResultUI extends Laya.Dialog {
		public avatar:Laya.Image;
		public amount:Laya.Label;
		public ticket:Laya.Label;
		public userName:Laya.Label;
		public userList:Laya.List;
		public loseTitile:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Result");
        }
    }
    export class SetUpUI extends Laya.Dialog {
		public btnSound:Laya.Button;
		public soundStatus:Laya.Clip;
		public btnFaq:Laya.Button;
		public btnNotice:Laya.Button;
		public noticeDot:Laya.Box;
		public btnSwitch:Laya.Button;
		public btnInvite:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/SetUp");
        }
    }
    export class SharePrizeUI extends Laya.Dialog {
		public sharePrizeCon:Laya.ViewStack;
		public btnShareInWX:Laya.Button;
		public btnShareToWX:Laya.Button;
		public btnShareToCircle:Laya.Button;
		public btnShareToQQ:Laya.Button;
		public btnShareToQZONE:Laya.Button;
		public btnShareToWeibo:Laya.Button;
		public canNotShare:Laya.Box;
		public btnDownload:Laya.Button;
		public btnDownloadIOS:Laya.Image;
		public btnDownloadAndroid:Laya.Image;
		public shareContent:laya.html.dom.HTMLDivElement;
		public shareSubContent:laya.html.dom.HTMLDivElement;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/SharePrize");
        }
    }
    export class ShareRecordsUI extends Laya.Dialog {
		public shareCon:Laya.ViewStack;
		public rewardsList:Laya.List;
		public recordsList:Laya.List;
		public shareTab:Laya.Tab;
		public noRecords:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/ShareRecords");
        }
    }
    export class SwitchPassPortUI extends Laya.Dialog {
		public userId:Laya.Label;
		public userSource:Laya.Label;
		public btnConfirm:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/SwitchPassPort");
        }
    }
    export class TrendUI extends Laya.Dialog {
		public bgimg:Laya.Image;
		public bgmask:Laya.Box;
		public mask2:Laya.Image;
		public mask1:Laya.Image;
		public trendCon:Laya.ViewStack;
		public trendList:Laya.List;
		public rateBox:Laya.Box;
		public rateShun:Laya.Label;
		public rateTian:Laya.Label;
		public rateDi:Laya.Label;
		public rateXuan:Laya.Label;
		public rateCount:Laya.Label;
		public richList:Laya.List;
		public trendTab:Laya.Tab;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Alert/Trend");
        }
    }
}
export module ui.views.Hall {
    export class HeaderUI extends Laya.View {
		public btnBack:Laya.Button;
		public avatar:Laya.Image;
		public userInfo:Laya.Box;
		public userName:Laya.Label;
		public userID:Laya.Label;
		public btnLogin:Laya.Label;
		public showGameScore:Laya.Image;
		public platformScore:Laya.Label;
		public btnRecharge:Laya.Button;
		public gameScore:Laya.Label;
		public btnGain:Laya.Button;
		public btnHome:Laya.Button;
		public btnSetup:Laya.Button;
		public btnShare:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Hall/Header");
        }
    }
    export class RankUI extends Laya.View {
		public rankTab:Laya.Tab;
		public rankCon:Laya.ViewStack;
		public rankPlayer:Laya.List;
		public playerNoData:Laya.Label;
		public rankMine:Laya.List;
		public mineNoData:Laya.Label;
		public btnNoLogin:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Hall/Rank");
        }
    }
    export class SceneUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Hall/Scene");
        }
    }
}
export module ui.views.Room {
    export class BankerUI extends Laya.View {
		public avatar:Laya.Image;
		public userName:Laya.Label;
		public userScore:Laya.Label;
		public btnOperateList:Laya.Button;
		public btnOperate:Laya.Button;
		public cardBox:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/Banker");
        }
    }
    export class BetUI extends Laya.View {
		public betList:Laya.List;
		public rightMask:Laya.Image;
		public leftMask:Laya.Image;
		public btnRepeat:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/Bet");
        }
    }
    export class BetAreaUI extends Laya.View {
		public betIcon:Laya.Image;
		public betTotal:Laya.Label;
		public betMineBox:Laya.Image;
		public betMine:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/BetArea");
        }
    }
    export class BetTotalUI extends Laya.View {
		public betTotal:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/BetTotal");
        }
    }
    export class CardUI extends Laya.View {
		public back:Laya.Image;
		public front:Laya.Image;
		public icon:Laya.Clip;
		public num:Laya.Clip;
		public joker:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/Card");
        }
    }
    export class CountDownUI extends Laya.View {
		public countDown:Laya.Box;
		public proBar:Laya.Image;
		public clock:Laya.Label;
		public waitForNext:Laya.Image;
		public waitTips:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/CountDown");
        }
    }
    export class PoolUI extends Laya.View {
		public poolLightBox:Laya.Box;
		public poolTotal:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/Pool");
        }
    }
    export class SceneUI extends Laya.Scene {
		public table:any;
		public headerArea:Laya.Box;
		public banker:any;
		public awardPool:any;
		public betTotal:any;
		public bottomArea:Laya.Box;
		public bet:any;
		public user:any;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/Scene");
        }
    }
    export class SeatUI extends Laya.View {
		public avatar:Laya.Image;
		public score:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/Seat");
        }
    }
    export class TableUI extends Laya.View {
		public bankerBorder:Laya.Image;
		public btnBack:Laya.Button;
		public btnShare:Laya.Button;
		public btnChat:Laya.Button;
		public btnSetup:Laya.Button;
		public btnPlayerList:Laya.Button;
		public btnTrend:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/Table");
        }
    }
    export class UserUI extends Laya.View {
		public avatar:Laya.Image;
		public userName:Laya.Label;
		public userScore:Laya.Label;
		public btnRecharge:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("views/Room/User");
        }
    }
}