var ASSETS = {
    Load : [
        {url : "res/load.json", type : Laya.Loader.ATLAS},

        {url : "res/load/bg.jpg", type : Laya.Loader.IMAGE},
        {url : "res/load/btn_share.sk", type : Laya.Loader.BUFFER},
        // {url : "res/load/load.png", type : Laya.Loader.IMAGE},
        // {url : "res/load/load.sk", type : Laya.Loader.BUFFER},
        {url : "res/load/notice.png", type : Laya.Loader.IMAGE},
    ],
    Hall : {
        Finished : false,
        Res : [
            {url : "res/avatar.json", type : Laya.Loader.ATLAS},
            {url : "res/hall.json", type : Laya.Loader.ATLAS},

            {url : "res/hall/bg_hall.jpg", type : Laya.Loader.IMAGE},
            {url : "res/hall/bg_header.png", type : Laya.Loader.IMAGE},
            {url : "res/hall/exchange.sk", type : Laya.Loader.BUFFER},
            {url : "res/hall/girl.png", type : Laya.Loader.IMAGE},
            {url : "res/hall/girl.sk", type : Laya.Loader.BUFFER},
            {url : "res/hall/quick_start.sk", type : Laya.Loader.BUFFER},
            {url : "res/hall/rank_bg.png", type : Laya.Loader.IMAGE},
            {url : "res/hall/room_1.sk", type : Laya.Loader.BUFFER},
            {url : "res/hall/room_2.sk", type : Laya.Loader.BUFFER},
            {url : "res/hall/room_3.sk", type : Laya.Loader.BUFFER},

            {url : "res/font/font_hall_rank.fnt", type : Laya.Loader.FONT},

            {url : "res/alert/public.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/recharge.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/gain.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/exchange.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/setup.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/share_prize.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/share_records.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/switch_passport.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/guide.json", type : Laya.Loader.ATLAS},

            {url : "res/alert/guide/guide_1.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/guide/guide_2.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/guide/guide_3.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/guide/guide_4.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/public/list_bg.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/setup/bg_setup.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/share_prize/share_prize.sk", type : Laya.Loader.BUFFER},
            {url : "res/alert/share_prize/share_prize.png", type : Laya.Loader.IMAGE},

            {url : "sound/bgm.mp3", type : Laya.Loader.SOUND},
            {url : "sound/btn.mp3", type : Laya.Loader.SOUND},
            {url : "sound/coin.mp3", type : Laya.Loader.SOUND},
            {url : "sound/countdown.mp3", type : Laya.Loader.SOUND},
            {url : "sound/lose.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_enght.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_five.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_four.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_nie.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_niu.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_one.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_seven.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_six.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_three.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_two.mp3", type : Laya.Loader.SOUND},
            {url : "sound/si_zha.mp3", type : Laya.Loader.SOUND},
            {url : "sound/win.mp3", type : Laya.Loader.SOUND},
            {url : "sound/wu_hua.mp3", type : Laya.Loader.SOUND},
            {url : "sound/wu_niu.mp3", type : Laya.Loader.SOUND},
        ]
    },
    Room : {
        Finished : false,
        Res : [
            {url : "res/avatar.json", type : Laya.Loader.ATLAS},
            {url : "res/room.json", type : Laya.Loader.ATLAS},

            {url : "res/room/banker_bg.png", type : Laya.Loader.IMAGE},
            {url : "res/room/card_type.sk", type : Laya.Loader.BUFFER},
            {url : "res/room/card_type.png", type : Laya.Loader.IMAGE},
            {url : "res/room/desk_bg.jpg", type : Laya.Loader.IMAGE},
            {url : "res/room/desk_border_bottom.png", type : Laya.Loader.IMAGE},
            {url : "res/room/desk_border_left.png", type : Laya.Loader.IMAGE},
            {url : "res/room/desk_border_right.png", type : Laya.Loader.IMAGE},
            {url : "res/room/desk_border_top.png", type : Laya.Loader.IMAGE},
            {url : "res/room/notify_bg.png", type : Laya.Loader.IMAGE},
            {url : "res/room/pool_light.sk", type : Laya.Loader.BUFFER},
            {url : "res/room/pool_light.png", type : Laya.Loader.IMAGE},

            {url : "res/font/font_award.fnt", type : Laya.Loader.FONT},
            {url : "res/font/font_bet_normal.fnt", type : Laya.Loader.FONT},
            {url : "res/font/font_bet_select.fnt", type : Laya.Loader.FONT},
            {url : "res/font/font_pool.fnt", type : Laya.Loader.FONT},
            {url : "res/font/font_result_lose.fnt", type : Laya.Loader.FONT},
            {url : "res/font/font_result_win.fnt", type : Laya.Loader.FONT},

            {url : "res/alert/public.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/award.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/chat.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/operate_list.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/operate_setup.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/player_list.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/prop.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/recharge.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/result.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/setup.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/share_prize.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/share_records.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/switch_passport.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/trend.json", type : Laya.Loader.ATLAS},
            {url : "res/alert/guide.json", type : Laya.Loader.ATLAS},

            {url : "res/alert/guide/guide_1.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/guide/guide_2.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/guide/guide_3.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/guide/guide_4.png", type : Laya.Loader.IMAGE},

            {url : "res/alert/result/lose_light.sk", type : Laya.Loader.BUFFER},
            {url : "res/alert/result/lose_light.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/result/result_lose.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/result/prize_light.sk", type : Laya.Loader.BUFFER},
            {url : "res/alert/result/prize_light.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/result/prize_title.sk", type : Laya.Loader.BUFFER},
            {url : "res/alert/result/prize_title.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/result/win_light.sk", type : Laya.Loader.BUFFER},
            {url : "res/alert/result/win_light.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/result/win_title.sk", type : Laya.Loader.BUFFER},
            {url : "res/alert/public/list_bg.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/setup/bg_setup.png", type : Laya.Loader.IMAGE},
            {url : "res/alert/share_prize/share_prize.sk", type : Laya.Loader.BUFFER},
            {url : "res/alert/share_prize/share_prize.png", type : Laya.Loader.IMAGE},

            {url : "sound/bgm.mp3", type : Laya.Loader.SOUND},
            {url : "sound/btn.mp3", type : Laya.Loader.SOUND},
            {url : "sound/coin.mp3", type : Laya.Loader.SOUND},
            {url : "sound/countdown.mp3", type : Laya.Loader.SOUND},
            {url : "sound/lose.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_enght.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_five.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_four.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_nie.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_niu.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_one.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_seven.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_six.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_three.mp3", type : Laya.Loader.SOUND},
            {url : "sound/niu_two.mp3", type : Laya.Loader.SOUND},
            {url : "sound/si_zha.mp3", type : Laya.Loader.SOUND},
            {url : "sound/win.mp3", type : Laya.Loader.SOUND},
            {url : "sound/wu_hua.mp3", type : Laya.Loader.SOUND},
            {url : "sound/wu_niu.mp3", type : Laya.Loader.SOUND},
        ]
    }
}

export default ASSETS;