/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.dialog {
    export class TestDialog1UI extends Laya.Dialog {
        public static  uiView:any ={"type":"Dialog","props":{"width":400,"runtime":"dialog/Dialog1.ts","height":300},"compId":2,"child":[{"type":"Image","props":{"y":10,"x":10,"top":0,"skin":"comp/img_bg.png","sizeGrid":"28,6,5,4","right":0,"left":0,"bottom":0},"compId":3},{"type":"Button","props":{"y":4,"x":366,"skin":"comp/btn_close.png","name":"close"},"compId":4},{"type":"Button","props":{"y":262,"x":254,"skin":"comp/button.png","name":"ok","label":"关闭按钮"},"compId":5},{"type":"Image","props":{"y":48,"x":44,"skin":"comp/image.png"},"compId":6},{"type":"Label","props":{"y":103,"x":188,"text":"对话框，内嵌模式","fontSize":24,"color":"#cf822f"},"compId":7}],"loadList":["comp/img_bg.png","comp/btn_close.png","comp/button.png","comp/image.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TestDialog1UI.uiView);
        }
    }
    REG("ui.dialog.TestDialog1UI",TestDialog1UI);
    export class TestDialog2UI extends Laya.Dialog {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("dialog/TestDialog2");
        }
    }
    REG("ui.dialog.TestDialog2UI",TestDialog2UI);
    export class TestDialog3UI extends Laya.Dialog {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("dialog/TestDialog3");
        }
    }
    REG("ui.dialog.TestDialog3UI",TestDialog3UI);
}
export module ui {
    export class loadViewUI extends Laya.Scene {
		public loading:Laya.ProgressBar;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("loadView");
        }
    }
    REG("ui.loadViewUI",loadViewUI);
}
export module ui.test {
    export class HallSceneUI extends Laya.Scene {
		public btnEnter:Laya.Button;
		public btnShowDialogByUrl:Laya.Button;
		public btnShowDialogByClass2:Laya.Button;
		public btnShowDialogByClass1:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/HallScene");
        }
    }
    REG("ui.test.HallSceneUI",HallSceneUI);
    export class testDialogUI extends Laya.Dialog {
		public btnBack:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/testDialog");
        }
    }
    REG("ui.test.testDialogUI",testDialogUI);
    export class TestSceneUI extends Laya.Scene {
		public scoreLbl:Laya.Label;
		public tipLbll:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}